### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [ProtonVPN/android-app#103]
Updating recipe, to remove the swan part... 
```
  - versionName: 4.4.73.0
    versionCode: 104047300
    commit: 0dfed59817a87e1d63cb72230cec6d18f3c944b5
    timeout: 7200
    subdir: app
    sudo:
      - apt-get update
      - apt-get install -y --no-install-recommends make libgmp-dev autoconf automake
        libtool pkg-config autogen gettext libssl-dev libsqlite3-dev libpam0g-dev
        libldap2-dev gperf bison bzip2 flex swig cmake
    gradle:
      - prod
    rm:
      - app/src/main/jniLibs/x86/*
      - app/src/main/jniLibs/x86_64/*
      - app/src/main/jniLibs/armeabi-v7a/*
      - app/src/main/jniLibs/arm64-v8a/*
      - openvpn/src/main/cpp/mbedtls/tests
      - openvpn/src/main/cpp/openvpn3/test/unittests
      - openvpn/src/main/cpp/mbedtls/programs/fuzz/corpuses/*
    prebuild:
      - sed -i -e '/triple/d' -e '/play\ {/,+4d' build.gradle
      - sed -i -e '/gradle-build-cache/d' ../settings.gradle.kts
    scandelete:
      - openvpn/src/main/cpp/lz4/tmp
    build:
      - pushd ../openvpn
      - gradle assembleRelease
      - rm -fr build/intermediates build/kotlin build/tmp .cxx
      - popd
    ndk: r23b
    gradleprops:
      - buildUniversalApk
```

but... now I'm missing some libs in the APK: `libipsec.so` and `libtncif.so` 

Thoughts?
